const fs=require('fs');
const {icons,fontface}=JSON.parse(fs.readFileSync('assets.json','utf8'));
let html=fs.readFileSync('pause.html','utf8');
html=html.replace('/*__FONT__*/', fontface);
html=html.replace('let ICONS_MS = {}; /*__ICONS__*/', 'let ICONS_MS = '+JSON.stringify(icons)+';');
const logo=JSON.parse(fs.readFileSync('logo.json','utf8'));
html=html.replaceAll('__PAUSE_FAVICON__', logo.fav);
html=html.replaceAll('__PAUSE_LOGO__', logo.logo);
html=html.replaceAll('__PAUSE_LOGO_DARK__', logo.logodark);
html=html.replaceAll('__PAUSE_LOCKUP__', logo.lockup);
html=html.replaceAll('__PAUSE_LOCKUP_DARK__', logo.lockupdark);
html=html.replaceAll('__PAUSE_APPICON__', logo.appicon);
if(html.includes('/*__FONT__*/')||html.includes('/*__ICONS__*/')||html.includes('__PAUSE_')) throw new Error('placeholder left');
fs.writeFileSync('pause.built.html', html);
console.log('built KB:', Math.round(fs.statSync('pause.built.html').size/1024), '| external refs:', (html.match(/https?:\/\/(?!www\.w3\.org)/g)||[]).length);
